### ISSUE TITLE
Newbie feedback

### ISSUE THREAD

**Issue by rsolari** [BruceEckel/HelloCookieCutter1#2]
As a brand-new cookiecutter user, I followed this tutorial to see whether any parts were confusing. Here are my notes.
- I was confused by the directory names that were curly brackets like `$ mkdir {{cookiecutter.directory_name}}` At first, I thought that I was supposed to substitute my own name into the brackets.
- I ran the cookiecutter command in the wrong directory. I didn't follow the instruction to "Move to a directory where you want to create the new project." Instead, I ran the command in the template directory. cookiecutter then tried to create the helloworld output inside the template directory. I got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/cli.py", line 106, in main
    config_file=user_config
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/main.py", line 145, in cookiecutter
    output_dir=output_dir
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 350, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 178, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
IOError: [Errno 2] No such file or directory: '~/projects/scratch/HelloCookieCutter1/{{cookiecutter.directory_name}}/Hello/Hello/Howdy.py'
```

The solution, of course, is to follow the instructions and run the cookiecutter command in the target directory. It took me a few minutes to figure that out because I was trying to understand why cookiecutter expected two nested `Hello` directories instead of a single `Hello` directory. 

Perhaps cookiecutter should throw an error or a warning when someone tries to execute the command inside the template directory.

After I ran the command outside the template directory, everything went swimmingly.

**Comment by BruceEckel** [comment]
Took care of the first issue by adding more prose. The second issue is about Cookiecutter itself so that would need reporting or pull-requesting on their site.
